<?php

declare(strict_types=1);

/**
 * Generate a Rector config wired to a testo/bridge-rector conversion set, scoped to the paths
 * you are migrating. Used in the Rector path of testo-migrate-from-phpunit.
 *
 * Write the config at the PROJECT ROOT (next to composer.json) — it uses `__DIR__`-relative
 * paths and expects `__DIR__` to be the project root.
 *
 * Usage:
 *   php scaffold-rector-config.php <outFile> --path=DIR [--path=DIR]... [--set=NAME] [--root=PATH] [--force]
 *
 * <outFile>     Config file to write, e.g. rector-testo-migration.php (kept separate from any
 *               existing rector.php so it can be deleted after the migration).
 * --path=DIR    Path Rector should process (repeatable). Required. Use the scope agreed in Phase 2.
 * --set=NAME    Conversion set basename (default: phpunit-to-testo). Must exist under the bridge.
 * --root=PATH   Project root (default: cwd) — used to locate vendor/ and to write the file.
 * --force       Overwrite <outFile> if it already exists.
 *
 * Writes the config file. Exit codes: 0 ok, 1 usage / refuse-overwrite, 2 autoload / bridge / set
 * not found.
 */

$out = null;
$paths = [];
$set = 'phpunit-to-testo';
$root = null;
$force = false;
foreach (\array_slice($argv, 1) as $arg) {
    if (\preg_match('/^--path=(.+)$/', $arg, $m)) {
        $paths[] = \str_replace('\\', '/', \rtrim($m[1], "/\\"));
    } elseif (\preg_match('/^--set=(.+)$/', $arg, $m)) {
        $set = \basename($m[1], '.php');
    } elseif (\preg_match('/^--root=(.+)$/', $arg, $m)) {
        $root = $m[1];
    } elseif ($arg === '--force') {
        $force = true;
    } elseif (!\str_starts_with($arg, '--')) {
        $out ??= $arg;
    } else {
        \fwrite(\STDERR, "unknown argument: {$arg}\n");
    }
}

$root = \rtrim($root ?? \getcwd(), "/\\");

if ($out === null || $paths === []) {
    \fwrite(\STDERR, "Usage: php scaffold-rector-config.php <outFile> --path=DIR [--path=DIR]... [--set=NAME] [--force]\n");
    exit(1);
}

$outAbs = \preg_match('#^(?:/|[A-Za-z]:[\\\\/])#', $out) === 1 ? $out : $root . '/' . $out;
if (\file_exists($outAbs) && !$force) {
    \fwrite(\STDERR, "Refusing to overwrite existing {$out} — pass --force to replace it.\n");
    exit(1);
}

// Resolve the chosen set through the bridge's typed handle (TestoRectorSetList) rather than a
// hard-coded path, so this script carries no knowledge of where the set files live. Needs the
// project autoloader — the bridge is a dev dependency installed in Stage A1.
$autoload = $root . '/vendor/autoload.php';
if (!\is_file($autoload)) {
    \fwrite(\STDERR, "No {$root}/vendor/autoload.php — run `composer install` first.\n");
    exit(2);
}
require $autoload;

$setListClass = \Testo\Bridge\Rector\Set\TestoRectorSetList::class;
if (!\class_exists($setListClass)) {
    \fwrite(\STDERR, "testo/bridge-rector is not installed. Try: composer require --dev testo/bridge-rector\n");
    exit(2);
}

// Set basename -> constant name: phpunit-to-testo -> PHPUNIT_TO_TESTO.
$setConst = \strtoupper(\str_replace('-', '_', $set));
$setListConst = "{$setListClass}::{$setConst}";
if (!\defined($setListConst)) {
    $available = \array_map(
        static fn(string $name): string => \strtolower(\str_replace('_', '-', $name)),
        \array_keys((new \ReflectionClass($setListClass))->getConstants()),
    );
    \fwrite(\STDERR, "Set not found: {$set}\nAvailable sets: " . \implode(', ', $available) . "\n");
    exit(2);
}

// The constant is an absolute path resolved by the installed bridge; make sure it exists before
// writing a config that would fatal at runtime.
$setPath = (string) \constant($setListConst);
if (!\is_file($setPath)) {
    \fwrite(\STDERR, "Set constant {$setConst} resolves to a missing file: {$setPath}\n");
    exit(2);
}

// Render --path values as __DIR__-relative entries (config lives at the project root).
$pathLines = \implode("\n", \array_map(
    static fn(string $p): string => "        __DIR__ . '/{$p}',",
    $paths,
));

// Built with concatenation rather than a heredoc so the generated file's indentation is exact
// and independent of this script's own indentation.
$config = "<?php\n\n"
    . "declare(strict_types=1);\n\n"
    . "/**\n"
    . " * Rector config for the PHPUnit -> Testo migration (set: {$set}).\n"
    . " *\n"
    . " * Generated by the testo-migrate-from-phpunit skill. This file is disposable: once the\n"
    . " * migration is verified under `vendor/bin/testo`, delete it (and the bridge from\n"
    . " * require-dev if you no longer need it).\n"
    . " *\n"
    . " * The set performs the MECHANICAL conversions only (assert calls + arg-order, lifecycle\n"
    . " * methods -> attributes, data providers, groups, #[CoversClass] -> #[Covers], bare\n"
    . " * expectException, markTestSkipped). It does NOT remove `extends TestCase`, reconcile test\n"
    . " * discovery, or convert mocks -- finish those with an AI/human pass (see the skill).\n"
    . " *\n"
    . " * Dry-run:  vendor/bin/rector process --config={$out} --dry-run\n"
    . " * Apply:    vendor/bin/rector process --config={$out}\n"
    . " */\n\n"
    . "use Rector\\Config\\RectorConfig;\n"
    . "use Testo\\Bridge\\Rector\\Set\\TestoRectorSetList;\n\n"
    . "return RectorConfig::configure()\n"
    . "    ->withPaths([\n"
    . "{$pathLines}\n"
    . "    ])\n"
    . "    ->withSets([\n"
    . "        TestoRectorSetList::{$setConst},\n"
    . "    ]);\n";

\file_put_contents($outAbs, $config);

echo "Wrote {$out}\n";
echo "  set:   {$set}\n";
echo "  paths: " . \implode(', ', $paths) . "\n\n";
echo "Next:\n";
echo "  vendor/bin/rector process --config={$out} --dry-run   # preview\n";
echo "  vendor/bin/rector process --config={$out}             # apply\n";

exit(0);
